version: '2'
services:
  web:
    container_name: intranet-sme
    image: php:5.6-apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
    - "localhost:127.0.0.1"
    links:
      - db:db
    volumes:
      - /var/www/html:/var/www/html
  db:
    container_name: intranet-sme-db
    image: mysql
    volumes:
     - /Users/clebersantos/Dev/project/db/mysql:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
      MYSQL_DATABASE: xxxx
